### ISSUE TITLE
点击不同宫位的连接线对应怎么做哦？

### ISSUE THREAD

**Issue by flywolfmaster** [haibolian/natal-chart#1]
点击不同宫位的连接线对应怎么做哦？

**Comment by haibolian** [comment]
@flywolfmaster 😅好久没看 github 了，添加点击事件，改下方法就好了，代码已更新：
<img width="1613" alt="image" src="https://user-images.githubusercontent.com/51857421/231041087-f57dd33a-efaa-4255-8a4f-95938ca385e9.png">
